export const categories = [
  {
    title: 'Смартфоны и гаджеты',
    uri: '/smartfony_i_gadzhety',
    slug: 'smartfony_i_gadzhety',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2FApple_iOS-update-iphone12pro-watchseries6-unlocking-screen_042621.png_8c2e44ef5a60e3dab90b4d45c8dfc342&w=48&q=75',
  },
  {
    title: 'Ноутбуки и компьютеры',
    uri: '/noutbuki_i_kompyutery',
    slug: 'noutbuki_i_kompyutery',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2FApple_iOS-update-iphone12pro-watchseries6-unlocking-screen_042621.png_7e9c29b98779f3e0c92076445260c828&w=48&q=75',
  },
  {
    title: 'Бытовая техника',
    uri: '/bytovaya_tekhnika',
    slug: 'bytovaya_tekhnika',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2FApple_iOS-update-iphone12pro-watchseries6-unlocking-screen_04262.png_e934f7bb08ef63ce2a56abbd921557d0&w=48&q=75',
  },
];

export const subCategoryParent = [
  {
    title: 'Смартфоны и телефоны',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony',
    slug: 'smartfony_i_telefony',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage141.png_bd0712b62609d255db4db2e75d499a61&w=32&q=75',
  },
  {
    title: 'Планшеты и электронные книги',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi',
    slug: 'planshety_i_elektronnyye_knigi',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage39%402x.png_d23ddbb211b792141b52cd50ae0db3b3&w=32&q=75',
  },
  {
    title: 'Гаджеты',
    uri: '/smartfony_i_gadzhety/gadzhety',
    slug: 'gadzhety',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage39%402x.png_fe1be4e878fc870524964a594e724835&w=32&q=75',
  },
  {
    title: 'Аксессуары для смартфонов',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov',
    slug: 'aksessuary_dlya_smartfonov',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage152.png_207e9c85c90b14f15bc8a0a479aa7d25&w=32&q=75',
  },
  {
    title: 'Наушники',
    uri: '/smartfony_i_gadzhety/naushniki',
    slug: 'naushniki',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage39.png_357c4d85ad5cbeefd773ad0b903096b7&w=32&q=75',
  },
  {
    title: 'Программное обеспечение',
    uri: '/smartfony_i_gadzhety/programmnoye_obespecheniye',
    slug: 'programmnoye_obespecheniye',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage36%402x.png_f8685e4a34076c980be09a631ee5cd9d&w=32&q=75',
  },
  {
    title: 'Умный дом',
    uri: '/smartfony_i_gadzhety/umnyy_dom',
    slug: 'umnyy_dom',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage142.png_380adec6cd2f8781cc103d33bb92596e&w=32&q=75',
  },
  {
    title: 'Ноутбуки и аксессуары',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary',
    slug: 'noutbuki_i_aksessuary',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage39%402x.png_05dec9e176e3dd046784c207e55326a3&w=32&q=75',
  },
  {
    title: 'Компьютеры и мониторы',
    uri: '/noutbuki_i_kompyutery/kompyutery_i_monitory',
    slug: 'kompyutery_i_monitory',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage30%402x.png_a2b388b77af8583c7cef55fd247f0f2a&w=32&q=75',
  },
  {
    title: 'Компьютерные аксессуары',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary',
    slug: 'kompyuternyye_aksessuary',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage32%402x.png_4b79708556b9af9bf37f118b504bd88b&w=32&q=75',
  },
  {
    title: 'Комплектующие',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye',
    slug: 'komplektuyushchiye',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage33.png_726247f4f737078e01d51684d59e217f&w=32&q=75',
  },
  {
    title: 'Холодильное и морозильное оборудование',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye',
    slug: 'kholodilnoye_i_morozilnoye_oborudovaniye',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage72.png_8fa34f5e0cd22cf59fbd59a150cd56a7&w=32&q=75',
  },
  {
    title: 'Уход за домом',
    uri: '/bytovaya_tekhnika/ukhod_za_domom',
    slug: 'ukhod_za_domom',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage73.png_2a6d148981666204fc713b65eb40fc45&w=32&q=75',
  },
  {
    title: 'Аксессуары к технике для дома',
    uri: '/bytovaya_tekhnika/aksessuary_k_tekhnike_dlya_doma',
    slug: 'aksessuary_k_tekhnike_dlya_doma',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage156%402x.png_d934da9cc588c083b192138bbcd6aff2&w=32&q=75',
  },
  {
    title: 'Рукоделие',
    uri: '/bytovaya_tekhnika/rukodeliye',
    slug: 'rukodeliye',
    iconUrl:
      'https://www.technodom.kz/_next/image?url=https%3A%2F%2Fapi.technodom.kz%2Ff3%2Fapi%2Fv1%2Fimages%2Fimage155%402x.png_c89abc140c9b12ede61130fe35d04a22&w=32&q=75',
  },
];

export const subCategoryChildren = [
  {
    title: 'Смартфоны',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony',
    slug: 'smartfony',
    parentId: 1,
  },
  {
    title: 'Смартфоны Samsung',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=samsung',
    slug: 'smartfony/brands=samsung',
    parentId: 1,
  },
  {
    title: 'Смартфоны Apple',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=apple',
    slug: 'smartfony/brands=apple',
    parentId: 1,
  },
  {
    title: 'Смартфоны HUAWEI',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=huawei',
    slug: 'smartfony/brands=huawei',
    parentId: 1,
  },
  {
    title: 'Смартфоны HONOR',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=honor',
    slug: 'smartfony/brands=honor',
    parentId: 1,
  },
  {
    title: 'Смартфоны Xiaomi',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=xiaomi',
    slug: 'smartfony/brands=xiaomi',
    parentId: 1,
  },
  {
    title: 'Смартфоны OPPO',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=oppo',
    slug: 'smartfony/brands=oppo',
    parentId: 1,
  },
  {
    title: 'Смартфоны Vivo',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=vivo',
    slug: 'smartfony/brands=vivo',
    parentId: 1,
  },
  {
    title: 'Смартфоны Motorola',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=motorola',
    slug: 'smartfony/brands=motorola',
    parentId: 1,
  },
  {
    title: 'Смартфоны Redmi',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=redmi',
    slug: 'smartfony/brands=redmi',
    parentId: 1,
  },
  {
    title: 'Смартфоны Poco',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=poco',
    slug: 'smartfony/brands=poco',
    parentId: 1,
  },
  {
    title: 'Смартфоны Tecno',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=tecno',
    slug: 'smartfony/brands=tecno',
    parentId: 1,
  },
  {
    title: 'Смартфоны Realme',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=realme',
    slug: 'smartfony/brands=realme',
    parentId: 1,
  },
  {
    title: 'Смартфоны Infinix',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=infinix',
    slug: 'smartfony/brands=infinix',
    parentId: 1,
  },
  {
    title: 'Мобильные телефоны',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/mobilnyye_telefony',
    slug: 'mobilnyye_telefony',
    parentId: 1,
  },
  {
    title: 'Смартфоны ZTЕ',
    uri: '/smartfony_i_gadzhety/smartfony_i_telefony/smartfony/brands=zte',
    slug: 'smartfony/brands=zte',
    parentId: 1,
  },
  {
    title: 'Планшеты',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi/planshety',
    slug: 'planshety',
    parentId: 2,
  },
  {
    title: 'Планшеты Samsung',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi/planshety/brands/samsung',
    slug: 'planshety_samsung',
    parentId: 2,
  },
  {
    title: 'Планшеты Apple iPad',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi/planshety/brands/apple',
    slug: 'planshety_apple_ipad',
    parentId: 2,
  },
  {
    title: 'Аксессуары для iPad',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi/aksessuary_dlya_ipad',
    slug: 'aksessuary_dlya_ipad',
    parentId: 2,
  },
  {
    title: 'Чехлы для планшетов',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi/chekhly_dlya_planshetov',
    slug: 'chekhly_dlya_planshetov',
    parentId: 2,
  },
  {
    title: 'Планшеты Lenovo',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi/planshety_lenovo',
    slug: 'planshety_lenovo',
    parentId: 2,
  },
  {
    title: 'Аксессуары для планшетов',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi/aksessuary_dlya_planshetov',
    slug: 'aksessuary_dlya_planshetov',
    parentId: 2,
  },
  {
    title: 'Электронные книги',
    uri: '/smartfony_i_gadzhety/planshety_i_elektronnyye_knigi/elektronnyye_knigi',
    slug: 'elektronnyye_knigi',
    parentId: 2,
  },
  {
    title: 'Смарт часы',
    uri: '/smartfony_i_gadzhety/gadzhety/smart_chasy',
    slug: 'smart_chasy',
    parentId: 3,
  },
  {
    title: 'Смарт часы Apple',
    uri: '/smartfony_i_gadzhety/gadzhety/smart_chasy_apple',
    slug: 'smart_chasy_apple',
    parentId: 3,
  },
  {
    title: 'Смарт часы Samsung',
    uri: '/smartfony_i_gadzhety/gadzhety/smart_chasy_samsung',
    slug: 'smart_chasy_samsung',
    parentId: 3,
  },
  {
    title: 'Смарт часы HUAWEI',
    uri: '/smartfony_i_gadzhety/gadzhety/smart_chasy_huawei',
    slug: 'smart_chasy_huawei',
    parentId: 3,
  },
  {
    title: 'Смарт часы Xiaomi',
    uri: '/smartfony_i_gadzhety/gadzhety/smart_chasy_xiaomi',
    slug: 'smart_chasy_xiaomi',
    parentId: 3,
  },
  {
    title: 'Аксессуары для смарт часов',
    uri: '/smartfony_i_gadzhety/gadzhety/aksessuary_dlya_smart_chasov',
    slug: 'aksessuary_dlya_smart_chasov',
    parentId: 3,
  },
  {
    title: 'Фитнес браслеты',
    uri: '/smartfony_i_gadzhety/gadzhety/fitnes_braslety',
    slug: 'fitnes_braslety',
    parentId: 3,
  },
  {
    title: 'Детские часы с GPS',
    uri: '/smartfony_i_gadzhety/gadzhety/detskiye_chasy_s_gps',
    slug: 'detskiye_chasy_s_gps',
    parentId: 3,
  },
  {
    title: 'Экшн-камеры',
    uri: '/smartfony_i_gadzhety/gadzhety/ekshn-kamery',
    slug: 'ekshn-kamery',
    parentId: 3,
  },
  {
    title: 'Аксессуары для экшн камер',
    uri: '/smartfony_i_gadzhety/gadzhety/aksessuary_dlya_ekshn_kamer',
    slug: 'aksessuary_dlya_ekshn_kamer',
    parentId: 3,
  },
  {
    title: 'Bluetooth-трекер',
    uri: '/smartfony_i_gadzhety/gadzhety/bluetooth-treker',
    slug: 'bluetooth-treker',
    parentId: 3,
  },

  {
    title: 'Умные колонки',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/umnyye_kolonki',
    slug: 'umnyye_kolonki',
    parentId: 4,
  },
  {
    title: 'Портативные колонки',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/portativnyye_kolonki',
    slug: 'portativnyye_kolonki',
    parentId: 4,
  },
  {
    title: 'Внешние аккумуляторы',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/vneshniye_akkumulyatory',
    slug: 'vneshniye_akkumulyatory',
    parentId: 4,
  },
  {
    title: 'Чехлы',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/chekhly',
    slug: 'chekhly',
    parentId: 4,
  },
  {
    title: 'Защита экрана',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/zashchita_ekrana',
    slug: 'zashchita_ekrana',
    parentId: 4,
  },
  {
    title: 'Карты памяти',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/karty_pamyati',
    slug: 'karty_pamyati',
    parentId: 4,
  },
  {
    title: 'Зарядные устройства',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/zaryadnyye_ustroystva',
    slug: 'zaryadnyye_ustroystva',
    parentId: 4,
  },
  {
    title: 'Беспроводные зарядные устройства',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/besprovodnyye_zaryadnyye_ustroystva',
    slug: 'besprovodnyye_zaryadnyye_ustroystva',
    parentId: 4,
  },
  {
    title: 'Кабели для смартфонов',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/kabeli_dlya_smartfonov',
    slug: 'kabeli_dlya_smartfonov',
    parentId: 4,
  },
  {
    title: 'Переходники для смартфонов',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/perekhodniki_dlya_smartfonov',
    slug: 'perekhodniki_dlya_smartfonov',
    parentId: 4,
  },
  {
    title: 'Авто аксессуары для смартфонов',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/avto_aksessuary_dlya_smartfonov',
    slug: 'avto_aksessuary_dlya_smartfonov',
    parentId: 4,
  },
  {
    title: 'Подставки',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/podstavki',
    slug: 'podstavki',
    parentId: 4,
  },
  {
    title: 'Селфи моноподы',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/selfi_monopody',
    slug: 'selfi_monopody',
    parentId: 4,
  },
  {
    title: 'Стабилизаторы (Стедикамы)',
    uri: '/smartfony_i_gadzhety/aksessuary_dlya_smartfonov/stabilizatory_stedikamy',
    slug: 'stabilizatory_stedikamy',
    parentId: 4,
  },

  {
    title: 'AirPods',
    uri: '/smartfony_i_gadzhety/naushniki/airpods',
    slug: 'airpods',
    parentId: 5,
  },
  {
    title: 'Наушники Xiaomi',
    uri: '/smartfony_i_gadzhety/naushniki/naushniki_xiaomi',
    slug: 'naushniki_xiaomi',
    parentId: 5,
  },
  {
    title: 'Беспроводные',
    uri: '/smartfony_i_gadzhety/naushniki/besprovodnyye',
    slug: 'besprovodnyye',
    parentId: 5,
  },
  {
    title: 'Проводные',
    uri: '/smartfony_i_gadzhety/naushniki/provodnyye',
    slug: 'provodnyye',
    parentId: 5,
  },
  {
    title: 'Все наушники',
    uri: '/smartfony_i_gadzhety/naushniki/vse_naushniki',
    slug: 'vse_naushniki',
    parentId: 5,
  },
  {
    title: 'Антивирусы и безопасность для смартфонов',
    uri: '/smartfony_i_gadzhety/programmnoye_obespecheniye/antivirusy_i_bezopasnost_dlya_smartfonov',
    slug: 'antivirusy_i_bezopasnost_dlya_smartfonov',
    parentId: 6,
  },
  {
    title: 'Офисные программы для смартфонов',
    uri: '/smartfony_i_gadzhety/programmnoye_obespecheniye/ofisnyye_programmy_dlya_smartfonov',
    slug: 'ofisnyye_programmy_dlya_smartfonov',
    parentId: 6,
  },
  {
    title: 'Учеба и развитие для смартфонов',
    uri: '/smartfony_i_gadzhety/programmnoye_obespecheniye/ucheba_i_razvitiye_dlya_smartfonov',
    slug: 'ucheba_i_razvitiye_dlya_smartfonov',
    parentId: 6,
  },
  {
    title: 'Онлайн-кинотеатры для смартфонов',
    uri: '/smartfony_i_gadzhety/programmnoye_obespecheniye/onlayn-kinoteatry_dlya_smartfonov',
    slug: 'onlayn-kinoteatry_dlya_smartfonov',
    parentId: 6,
  },
  {
    title: 'Удаленный сервис для смартфонов',
    uri: '/smartfony_i_gadzhety/programmnoye_obespecheniye/udalennyy_servis_dlya_smartfonov',
    slug: 'udalennyy_servis_dlya_smartfonov',
    parentId: 6,
  },
  {
    title: 'Блокировщики рекламы',
    uri: '/smartfony_i_gadzhety/programmnoye_obespecheniye/blokirovshchiki_reklamy',
    slug: 'blokirovshchiki_reklamy',
    parentId: 6,
  },
  {
    title: 'Родительский контроль',
    uri: '/smartfony_i_gadzhety/programmnoye_obespecheniye/roditelskiy_kontrol',
    slug: 'roditelskiy_kontrol',
    parentId: 6,
  },

  {
    title: 'Умный дом Xiaomi',
    uri: '/smartfony_i_gadzhety/umnyy_dom/umnyy_dom_xiaomi',
    slug: 'umnyy_dom_xiaomi',
    parentId: 7,
  },
  {
    title: 'Управление для умного дома',
    uri: '/smartfony_i_gadzhety/umnyy_dom/upravleniye_dlya_umnogo_doma',
    slug: 'upravleniye_dlya_umnogo_doma',
    parentId: 7,
  },
  {
    title: 'Пульты управления для умного дома',
    uri: '/smartfony_i_gadzhety/umnyy_dom/pulty_upravleniya_dlya_umnogo_doma',
    slug: 'pulty_upravleniya_dlya_umnogo_doma',
    parentId: 7,
  },
  {
    title: 'Умные лампы',
    uri: '/smartfony_i_gadzhety/umnyy_dom/umnyye_lampy',
    slug: 'umnyye_lampy',
    parentId: 7,
  },
  {
    title: 'Умные розетки',
    uri: '/smartfony_i_gadzhety/umnyy_dom/umnyye_rozetki',
    slug: 'umnyye_rozetki',
    parentId: 7,
  },
  {
    title: 'Датчики',
    uri: '/smartfony_i_gadzhety/umnyy_dom/datchiki',
    slug: 'datchiki',
    parentId: 7,
  },
  {
    title: 'Яндекс (Алиса)',
    uri: '/smartfony_i_gadzhety/umnyy_dom/yandeks_alisa',
    slug: 'yandeks_alisa',
    parentId: 7,
  },
  {
    title: 'Ноутбуки',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/noutbuki',
    slug: 'noutbuki',
    parentId: 8,
  },
  {
    title: 'Игровые ноутбуки',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/igrovyye_noutbuki',
    slug: 'igrovyye_noutbuki',
    parentId: 8,
  },
  {
    title: 'Apple MacBook',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/apple_macbook',
    slug: 'apple_macbook',
    parentId: 8,
  },
  {
    title: 'Сумки',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/sumki',
    slug: 'sumki',
    parentId: 8,
  },
  {
    title: 'Рюкзаки',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/ryukzaki',
    slug: 'ryukzaki',
    parentId: 8,
  },
  {
    title: 'Чехлы для ноутбуков',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/chekhly_dlya_noutbukov',
    slug: 'chekhly_dlya_noutbukov',
    parentId: 8,
  },
  {
    title: 'Подставки для ноутбуков',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/podstavki_dlya_noutbukov',
    slug: 'podstavki_dlya_noutbukov',
    parentId: 8,
  },
  {
    title: 'Зарядные устройства для ноутбуков',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/zaryadnyye_ustroystva_dlya_noutbukov',
    slug: 'zaryadnyye_ustroystva_dlya_noutbukov',
    parentId: 8,
  },
  {
    title: 'Кабели и адаптеры для ноутбуков и ПК',
    uri: '/noutbuki_i_kompyutery/noutbuki_i_aksessuary/kabeli_i_adaptery_dlya_noutbukov_i_pk',
    slug: 'kabeli_i_adaptery_dlya_noutbukov_i_pk',
    parentId: 8,
  },

  {
    title: 'Компьютеры',
    uri: '/noutbuki_i_kompyutery/kompyutery_i_monitory/kompyutery',
    slug: 'kompyutery',
    parentId: 9,
  },
  {
    title: 'Игровые компьютеры',
    uri: '/noutbuki_i_kompyutery/kompyutery_i_monitory/igrovyye_kompyutery',
    slug: 'igrovyye_kompyutery',
    parentId: 9,
  },
  {
    title: 'Компьютеры TechnoGaming',
    uri: '/noutbuki_i_kompyutery/kompyutery_i_monitory/kompyutery_technogaming',
    slug: 'kompyutery_technogaming',
    parentId: 9,
  },
  {
    title: 'Моноблоки',
    uri: '/noutbuki_i_kompyutery/kompyutery_i_monitory/monobloki',
    slug: 'monobloki',
    parentId: 9,
  },
  {
    title: 'Моноблоки Apple iMac',
    uri: '/noutbuki_i_kompyutery/kompyutery_i_monitory/monobloki_apple_imac',
    slug: 'monobloki_apple_imac',
    parentId: 9,
  },
  {
    title: 'Мониторы',
    uri: '/noutbuki_i_kompyutery/kompyutery_i_monitory/monitory',
    slug: 'monitory',
    parentId: 9,
  },
  {
    title: 'Крепления и стойки',
    uri: '/noutbuki_i_kompyutery/kompyutery_i_monitory/krepleniya_i_stoyki',
    slug: 'krepleniya_i_stoyki',
    parentId: 9,
  },

  {
    title: 'Мыши',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/myshi',
    slug: 'myshi',
    parentId: 10,
  },
  {
    title: 'Клавиатуры',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/klaviatury',
    slug: 'klaviatury',
    parentId: 10,
  },
  {
    title: 'Комплект клавиатура + мышь',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/komplekt_klaviatura_i_mysh',
    slug: 'komplekt_klaviatura_i_mysh',
    parentId: 10,
  },
  {
    title: 'Коврики для мыши',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/kovriki_dlya_myshi',
    slug: 'kovriki_dlya_myshi',
    parentId: 10,
  },
  {
    title: 'Веб-камеры',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/veb-kamery',
    slug: 'veb-kamery',
    parentId: 10,
  },
  {
    title: 'Камеры для конференц-залов',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/kamery_dlya_konferents-zalov',
    slug: 'kamery_dlya_konferents-zalov',
    parentId: 10,
  },
  {
    title: 'Гарнитуры',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/garnitury',
    slug: 'garnitury',
    parentId: 10,
  },
  {
    title: 'Колонки для ПК',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/kolonki_dlya_pk',
    slug: 'kolonki_dlya_pk',
    parentId: 10,
  },
  {
    title: 'UPS (источники бесперебойного питания)',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/ups_istochniki_bespereboynogo_pitaniya',
    slug: 'ups_istochniki_bespereboynogo_pitaniya',
    parentId: 10,
  },
  {
    title: 'Стабилизаторы напряжения',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/stabilizatory_napryazheniya',
    slug: 'stabilizatory_napryazheniya',
    parentId: 10,
  },
  {
    title: 'Сетевые фильтры',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/setevyye_filtry',
    slug: 'setevyye_filtry',
    parentId: 10,
  },
  {
    title: 'Чистящие средства',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/chistyashchiye_sredstva',
    slug: 'chistyashchiye_sredstva',
    parentId: 10,
  },
  {
    title: 'Графические планшеты',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/graficheskiye_planshety',
    slug: 'graficheskiye_planshety',
    parentId: 10,
  },
  {
    title: 'Адаптеры Bluetooth',
    uri: '/noutbuki_i_kompyutery/kompyuternyye_aksessuary/adaptery_bluetooth',
    slug: 'adaptery_bluetooth',
    parentId: 10,
  },

  {
    title: 'Процессоры',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/protsessory',
    slug: 'protsessory',
    parentId: 11,
  },
  {
    title: 'Материнские платы',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/materinskiye_platy',
    slug: 'materinskiye_platy',
    parentId: 11,
  },
  {
    title: 'Видеокарты',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/videokarty',
    slug: 'videokarty',
    parentId: 11,
  },
  {
    title: 'Оперативная память',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/operativnaya_pamyat',
    slug: 'operativnaya_pamyat',
    parentId: 11,
  },
  {
    title: 'SSD диски',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/ssd_diski',
    slug: 'ssd_diski',
    parentId: 11,
  },
  {
    title: 'Кулеры для процессоров',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/kulery_dlya_protsessorov',
    slug: 'kulery_dlya_protsessorov',
    parentId: 11,
  },
  {
    title: 'Системы жидкостного охлаждения',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/sistemy_zhidkostnogo_okhlazhdeniya',
    slug: 'sistemy_zhidkostnogo_okhlazhdeniya',
    parentId: 11,
  },
  {
    title: 'Блоки питания',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/bloki_pitaniya',
    slug: 'bloki_pitaniya',
    parentId: 11,
  },
  {
    title: 'Кейсы',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/keysy',
    slug: 'keysy',
    parentId: 11,
  },
  {
    title: 'Кулеры для кейса',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/kulery_dlya_keysa',
    slug: 'kulery_dlya_keysa',
    parentId: 11,
  },
  {
    title: 'Кастомное водяное охлаждение',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/kastomnoye_vodyanoye_okhlazhdeniye',
    slug: 'kastomnoye_vodyanoye_okhlazhdeniye',
    parentId: 11,
  },
  {
    title: 'Термопасты',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/termopasty',
    slug: 'termopasty',
    parentId: 11,
  },
  {
    title: 'Звуковые карты',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/zvukovyye_karty',
    slug: 'zvukovyye_karty',
    parentId: 11,
  },
  {
    title: 'Аксессуары для комплектующих',
    uri: '/noutbuki_i_kompyutery/komplektuyushchiye/aksessuary_dlya_komplektuyushchikh',
    slug: 'aksessuary_dlya_komplektuyushchikh',
    parentId: 11,
  },
  {
    title: 'Холодильники',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/kholodilniki',
    slug: 'kholodilniki',
    parentId: 12,
  },
  {
    title: 'Холодильники Hotpoint',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/kholodilniki_hotpoint',
    slug: 'kholodilniki_hotpoint',
    parentId: 12,
  },
  {
    title: 'Холодильники для хранения напитков',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/kholodilniki_dlya_khraneniya_napitkov',
    slug: 'kholodilniki_dlya_khraneniya_napitkov',
    parentId: 12,
  },
  {
    title: 'Холодильники для шуб',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/kholodilniki_dlya_shub',
    slug: 'kholodilniki_dlya_shub',
    parentId: 12,
  },
  {
    title: 'Холодильники для ферментации мяса',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/kholodilniki_dlya_fermentatsii_myasa',
    slug: 'kholodilniki_dlya_fermentatsii_myasa',
    parentId: 12,
  },
  {
    title: 'Морозильные камеры',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/morozilnyye_kamery',
    slug: 'morozilnyye_kamery',
    parentId: 12,
  },
  {
    title: 'Аксессуары для холодильников',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/aksessuary_dlya_kholodilnikov',
    slug: 'aksessuary_dlya_kholodilnikov',
    parentId: 12,
  },
  {
    title: 'Вакууматоры',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/vakuumatory',
    slug: 'vakuumatory',
    parentId: 12,
  },
  {
    title: 'Бытовая химия для холодильников',
    uri: '/bytovaya_tekhnika/kholodilnoye_i_morozilnoye_oborudovaniye/bytovaya_khimiya_dlya_kholodilnikov',
    slug: 'bytovaya_khimiya_dlya_kholodilnikov',
    parentId: 12,
  },

  {
    title: 'Пылесосы Dreame',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/pylesosy_dreame',
    slug: 'pylesosy_dreame',
    parentId: 13,
  },
  {
    title: 'Пылесосы',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/pylesosy',
    slug: 'pylesosy',
    parentId: 13,
  },
  {
    title: 'Вертикальные пылесосы',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/vertikalnyye_pylesosy',
    slug: 'vertikalnyye_pylesosy',
    parentId: 13,
  },
  {
    title: 'Робот-пылесосы',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/robot-pylesosy',
    slug: 'robot-pylesosy',
    parentId: 13,
  },
  {
    title: 'Моющие пылесосы',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/moyushchiye_pylesosy',
    slug: 'moyushchiye_pylesosy',
    parentId: 13,
  },
  {
    title: 'Аксессуары для пылесосов',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/aksessuary_dlya_pylesosov',
    slug: 'aksessuary_dlya_pylesosov',
    parentId: 13,
  },
  {
    title: 'Мойки высокого давления',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/moyki_vysokogo_davleniya',
    slug: 'moyki_vysokogo_davleniya',
    parentId: 13,
  },
  {
    title: 'Аксессуары для моек высокого давления',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/aksessuary_dlya_moyek_vysokogo_davleniya',
    slug: 'aksessuary_dlya_moyek_vysokogo_davleniya',
    parentId: 13,
  },
  {
    title: 'Мойщики окон',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/moyshchiki_okon',
    slug: 'moyshchiki_okon',
    parentId: 13,
  },
  {
    title: 'Пароочистители',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/paroochistiteli',
    slug: 'paroochistiteli',
    parentId: 13,
  },
  {
    title: 'Аксессуары для мойщиков окон',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/aksessuary_dlya_moyshchikov_okon',
    slug: 'aksessuary_dlya_moyshchikov_okon',
    parentId: 13,
  },
  {
    title: 'Швабры и ведра',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/shvabry_i_vedra',
    slug: 'shvabry_i_vedra',
    parentId: 13,
  },
  {
    title: 'Принадлежности для уборки',
    uri: '/bytovaya_tekhnika/ukhod_za_domom/prinadlezhnosti_dlya_uborki',
    slug: 'prinadlezhnosti_dlya_uborki',
    parentId: 13,
  },

  {
    title: 'Аксессуары для утюгов и гладильных досок',
    uri: '/bytovaya_tekhnika/aksessuary_k_tekhnike_dlya_doma/aksessuary_dlya_utyugov_i_gladilnykh_dosok',
    slug: 'aksessuary_dlya_utyugov_i_gladilnykh_dosok',
    parentId: 14,
  },
  {
    title: 'Аксессуары для стиральных и сушильных машин',
    uri: '/bytovaya_tekhnika/aksessuary_k_tekhnike_dlya_doma/aksessuary_dlya_stiralnykh_i_sushilnykh_mashin',
    slug: 'aksessuary_dlya_stiralnykh_i_sushilnykh_mashin',
    parentId: 14,
  },
  {
    title: 'Машинки для удаления катышков',
    uri: '/bytovaya_tekhnika/aksessuary_k_tekhnike_dlya_doma/mashinki_dlya_udaleniya_katyshkov',
    slug: 'mashinki_dlya_udaleniya_katyshkov',
    parentId: 14,
  },
  {
    title: 'Бытовая химия для стиральных машин',
    uri: '/bytovaya_tekhnika/aksessuary_k_tekhnike_dlya_doma/bytovaya_khimiya_dlya_stiralnykh_mashin',
    slug: 'bytovaya_khimiya_dlya_stiralnykh_mashin',
    parentId: 14,
  },

  {
    title: 'Швейные машины',
    uri: '/bytovaya_tekhnika/rukodeliye/Shveynyye mashiny',
    slug: 'Shveynyye mashiny',
    parentId: 15,
  },
  {
    title: 'Оверлоки',
    uri: '/bytovaya_tekhnika/rukodeliye/Overloki',
    slug: 'Overloki',
    parentId: 15,
  },
  {
    title: 'Аксессуары для швейных машин',
    uri: '/bytovaya_tekhnika/rukodeliye/Aksessuary dlya shveynykh mashin',
    slug: 'Aksessuary dlya shveynykh mashin',
    parentId: 15,
  },
  {
    title: 'Портновские манекены',
    uri: '/bytovaya_tekhnika/rukodeliye/Portnovskiye manekeny',
    slug: 'Portnovskiye manekeny',
    parentId: 15,
  },
  {
    title: 'Портновские колодки',
    uri: '/bytovaya_tekhnika/rukodeliye/Portnovskiye kolodki',
    slug: 'Portnovskiye kolodki',
    parentId: 15,
  },
];
